CREATE SCHEMA IF NOT EXISTS logins;
CREATE SCHEMA IF NOT EXISTS requesters;
CREATE SCHEMA IF NOT EXISTS consultants;
CREATE SCHEMA IF NOT EXISTS consultancies;
CREATE SCHEMA IF NOT EXISTS logs;

-- Functions
CREATE SCHEMA IF NOT EXISTS helpers;

-- Extensions
CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto
    WITH SCHEMA extensions;
