CREATE SCHEMA IF NOT EXISTS logins;
CREATE SCHEMA IF NOT EXISTS requesters;
CREATE SCHEMA IF NOT EXISTS consultants;
CREATE SCHEMA IF NOT EXISTS consultancies;
CREATE SCHEMA IF NOT EXISTS logs;

CREATE SCHEMA IF NOT EXISTS ext_pgcrypto;
CREATE EXTENSION IF NOT EXISTS pgcrypto
    WITH SCHEMA ext_pgcrypto;
